# config/meta.yml

meta_product_name: "NotifiQ"
meta_title: "NotifiQ - Don't wait in Line!"
meta_description: "Tired of waiting in line? Use your time optimally, and scan the QR Code!"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
